version: '3.8'

services:
  web:
    build: .
    ports:
      - "8005:8005"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=1
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8005 --reload"

volumes:
  static_volume:
  media_volume:
