# Generated by Django 5.2.5 on 2025-08-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerHistory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogXML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacao', models.CharField(max_length=30)),
                ('cliente_id', models.CharField(blank=True, max_length=100, null=True)),
                ('xml_recebido', models.TextField()),
                ('xml_enviado', models.TextField()),
                ('status_code', models.IntegerField()),
                ('sucesso', models.BooleanField(default=True)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
